spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zagzag?serverTimezone=UTC
    username: root
    password: thddmswl7
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: debug
    root: debug